### ISSUE TITLE
Feature Request: Soft Targeting on Party List

### ISSUE THREAD

**Issue by P3nke** [meoiswa/MagitekStratagem#1]
Hey, thank you for making this. As a healer main I was thinking that it would be really cool to heal someone just by looking at them in the party list. I wonder if that would be possible.

**Comment by meoiswa** [comment]
Unfortunately this isnt possible as the targeting requires collision detection (using ray casting) to in-game actors. It does not support interacting with the UI elements.
I'll ask the developers who are more experienced with UI if there might be a way to achieve this by drawing custom party frames on the screen, but this would be a long ways off in the future
