### ISSUE TITLE
Plugin causing black screen

### ISSUE THREAD

**Issue by sSsPRODIGYsSs** [meoiswa/MagitekStratagem#3]
When i turn the pugin on it makes the screen black. I was able to put the game in windowed mode and it looks like when the plugin is on it makes a black window over the game itself. I can see the game running fine and fully visible form the taskbar preview but when i click into the game everything is covered with teh black overlay. Any hlep is appreciated.

**Comment by meoiswa** [comment]
For now, to get you back in game, you can do the following:
Holding shift when opening XIVLauncher will allow you to right click the login button and launch the game with plugins disabled (not Dalamud), so you can uninstall it.

I'll look into the issue, I've already been hinted by more experienced developers that I may have made an error in my Overlay Window code that could cause issues if Dalamud's Multi Monitor Mode is enabled.

**Comment by meoiswa** [comment]
Fixed in v0.4.1.0 - Pending PAC aproval (b1e0fbd33bbab07316fd51f571cd19e24f141a5a)
