### ISSUE TITLE
Can't start tracking

### ISSUE THREAD

**Issue by doonga** [meoiswa/MagitekStratagem#5]
I've been trying this out to see if I could get it working. I think I have everything set properly. However, when I click 'start tracking' I see this in /xllog:

15:46:30.330 | VRB | WindowSystem "MagitekStratagemPlugin" Window "MagitekStratagem##ConfigWindow" has focus now
15:46:30.413 | DBG | [MagitekStratagem] Failed to track window.

I have Tobii Experience and Tobii Game Hub installed. Not sure what to look at next...

**Comment by meoiswa** [comment]
Some troubleshooting:
- Tobii Game Hub is running with the same privileges as FFXIV.
- Tobii Game Hub version 3.3.0 or newer
- You've accepted the EULA and calibrated your tracker
- That the tracker works with other games
- Firewall/Antivirus shenanigans?
- Enable Verbose logging in /xllog to see if something else is failing in the process of acquiring tracking data from Tobii

**Comment by doonga** [comment]
- Yep neither run as admin
- Game Hub 3.4.1-ci2
- Accepted and Calibrated
- Other games may be problematic... it works in some, but I also see that error in the game hub when another one is running, I was testing with a few of the free apps.
- Nothing notable for firewall/antivirus logs
- What I pasted above was the verbose log

I'll poke at this some more, the fact that it's showing a similar error for other games leads me to believe something else is messed up. I'll come back here if this ends up being the only thing not working.

**Comment by Alvatore** [comment]
I am also having this issue. It was working fine for me on the 8th when I installed it, but today the 16th I notice it's not working anymore. It's giving the same "failed to track window" error that doonga has mentioned. All troubleshooting list items check green.

**Comment by meoiswa** [comment]
Can confirm my Tobii Game Hub got updated (its a different icon) and I'm having the same issue now. Will try to fix.

**Comment by meoiswa** [comment]
Deploying a build that will attempt to load the DLL from v3.3.0 of Tobii Game Hub, should it still be available on the system. As the Squirrel Updater they use doesn't remove the older version, it should be present for players that had the plugin work before.
See [Dalamud's Discord Forum Post](https://discord.com/channels/581875019861328007/1161602613272391730/1262921649930633218) for more info

**Comment by meoiswa** [comment]
Fixed on v0.6 with the change to Tobii Streams API

**Comment by doonga** [comment]
Finally got back around to this, but yes this was indeed fixed with 0.6. Thank you!
