### ISSUE TITLE
Alternative Eye Tracker Support

### ISSUE THREAD

**Issue by HEKnTEKn** [meoiswa/MagitekStratagem#6]
Hello!

I was wondering if this plugin might conceivably receive support for alternative eye tracking software, such as [Beam Eye Tracker](https://beam.eyeware.tech/)?

I don't own a Tobii but feel like this could be a revolutionary plugin, especially for playing on controller to help target allies as a healer for example.

Thank you so much for your time, and I just want to say you're awesome for working on this kind of idea in the first place!

**Comment by meoiswa** [comment]
The plugin was designed specifically to support more types of trackers, as long as they conform to the [ITracker Interface](https://github.com/meoiswa/MagitekStratagem/blob/main/MagitekStratagem/ITrackerService.cs)

```c#
public interface ITrackerService : IDisposable
{
    // Infroms the plugin if the tracker is, well, tracking. I/E if data is being read successfully
    bool IsTracking { get; }
    // Newest available data will be read through these getters:
    long LastGazeTimestamp { get; }
    float LastGazeX { get; }
    float LastGazeY { get; }
    // Called by the UI when the users wants to start/stop tracking, or when the game's ready if using auto-start. 
    // Use these to start/stop any out-of-process or async calls to the tracker API.
    void StartTracking();
    void StopTracking();
    // Called every Dalamud Framework Update. Use this to do any in-process / locking calls to the tracker API.
    void Update();
    // Called by the UI loop when its open or the "Always show overlay" is enabled. Useful for painting informational markers.
    virtual void Draw() { }
}
``` 

Reading Eyeware Beam's Licensing agreements, I don't any blockers for adopting their API (No conflicts with Tobii licensing)
However, their API has no C# bindings, so porting the required functionality might be tricky.
Not any trickier than Tobii was, at least.
I see they have a free Demo on Steam, hopefully I can use that to develop the solution.

**Comment by meoiswa** [comment]
Added Eye ware Beam tracker support in v0.7

**Comment by HEKnTEKn** [comment]
Holy cow that was fast. Thank you so much for taking it into consideration and making it a reality. You absolutely rock!

Do you have a ko-fi or anything like that?
